const {config,e,t,wa,money,icon}=require('./shared.cjs');

function renderEnquiry(lang) {
  const b=config.business;
  return `<section class="section enquiry-section" id="semak-tarikh" aria-labelledby="enquiryTitle"><div class="wrap enquiry-layout">
    <div><p class="eyebrow">${t(lang,'BINCANG DENGAN OWNER','LET’S PLAN YOUR STAY')}</p><h2 id="enquiryTitle">${t(lang,'Dah ada tarikh<br>dalam fikiran?','Have a date<br>in mind?')}</h2><p>${t(lang,'Tanya terus melalui WhatsApp, atau sediakan butiran di sini. Anda boleh semak anggaran dan mesej sebelum membukanya di WhatsApp.','Ask directly on WhatsApp, or prepare the details here. Review the estimate and your message before opening it in WhatsApp.')}</p><a class="button button-light" href="${wa(lang)}" target="_blank" rel="noopener">WhatsApp ${icon('arrow')}</a><a class="enquiry-phone" href="tel:+${b.phone}">${icon('phone')}${e(b.phoneDisplay)}</a><p class="enquiry-note">${t(lang,'Owner akan sahkan tarikh dan harga akhir. Tiada tempahan atau bayaran dibuat di website.','The owner confirms dates and the final price. No booking or payment is made on this website.')}</p></div>
    <div class="enquiry-panel"><noscript><p>${t(lang,'Gunakan pautan WhatsApp atau telefon untuk bertanya tentang tarikh, bilik dan jumlah tetamu.','Use the WhatsApp or phone link to discuss dates, room packages and guest count.')}</p></noscript>
    <form id="dateForm" hidden><h3 id="enquiryFormTitle" tabindex="-1">${t(lang,'Sediakan pertanyaan anda','Prepare your enquiry')}</h3>
      <div id="enquiryPackage" class="enquiry-package" hidden><div id="enquiryPackageDetails" role="status" aria-live="polite" aria-atomic="true"><span class="enquiry-package-label">${t(lang,'Pakej semasa','Current package')}</span><strong id="enquiryPackageName"></strong><p id="enquiryPackageMeta"></p></div><a id="changeEnquiryPackage" href="#kadar">${t(lang,'Tukar pakej','Change package')} ${icon('arrow')}</a></div>
      <div class="form-grid">
        <div><label for="checkin">Check-in</label><input id="checkin" name="checkin" type="date" required aria-describedby="checkinError"><p class="field-error" id="checkinError" hidden></p></div>
        <div><label for="checkout">Check-out</label><input id="checkout" name="checkout" type="date" required aria-describedby="checkoutError"><p class="field-error" id="checkoutError" hidden></p></div>
      </div>
      <div id="stayShortcuts" class="stay-shortcuts" hidden><span>${t(lang,'Isi check-out untuk','Set check-out for')}</span><div>${[1,2,3].map(n=>`<button type="button" data-nights="${n}" aria-pressed="false">${n} ${t(lang,'malam',n===1?'night':'nights')}</button>`).join('')}</div></div>
      <div class="form-grid guest-fields">
        <div><label for="guests">${t(lang,'Jumlah tetamu','Guest count')}</label><input id="guests" name="guests" type="number" inputmode="numeric" min="1" max="${b.maxGuests}" step="1" value="6" required aria-describedby="guestHint guestsError"><p class="field-error" id="guestsError" hidden></p></div>
        <div><label for="rooms">${t(lang,'Pakej bilik','Room package')}</label><select id="rooms" name="rooms" required aria-describedby="roomsError">${config.rates.map(rate=>`<option value="${rate.rooms}" data-bathrooms="${rate.bathrooms}">${rate.rooms} ${t(lang,'bilik','rooms')} · ${money(rate.price)}/${t(lang,'malam','night')}</option>`).join('')}</select><p class="field-error" id="roomsError" hidden></p></div>
      </div>
      <p id="guestHint" class="field-note">${t(lang,`Maksimum ${b.maxGuests} orang termasuk kanak-kanak.`, `Maximum ${b.maxGuests} guests, including children.`)}</p>
      <div class="deposit-choice"><label for="depositCategory">${t(lang,'Kategori deposit','Deposit category')}</label><select id="depositCategory" name="depositCategory" aria-describedby="depositCategoryHint"><option value="standard">${t(lang,`Biasa / kecil · ${money(b.securityDeposit)}`,`Regular / small · ${money(b.securityDeposit)}`)}</option><option value="large">${t(lang,`Besar / majlis · ${money(b.largeGroupSecurityDeposit)}`,`Large / event · ${money(b.largeGroupSecurityDeposit)}`)}</option></select><p class="field-note" id="depositCategoryHint">${t(lang,`${money(b.securityDeposit)} untuk penginapan biasa atau kumpulan kecil. ${money(b.largeGroupSecurityDeposit)} untuk rombongan besar atau majlis besar seperti kenduri dengan ramai penghuni. Owner akan sahkan kategori semasa tempahan.`,`${money(b.securityDeposit)} for regular stays or small groups. ${money(b.largeGroupSecurityDeposit)} for large groups or major events such as weddings with many occupants. The owner will confirm the category when booking.`)}</p></div>
      <label for="notes">${t(lang,'Nota tambahan','Additional notes')} <span class="optional">(${t(lang,'pilihan','optional')})</span></label><textarea id="notes" name="notes" rows="2" maxlength="1000" placeholder="${t(lang,'Contoh: keperluan bilik di tingkat bawah','For example: a downstairs bedroom request')}"></textarea>
      <div id="priceEstimate" class="price-estimate" role="status" aria-live="polite"><p id="estimatePrompt">${t(lang,'Pilih tarikh dan pakej untuk lihat sewaan + deposit = jumlah bayaran awal.','Choose dates and a package to see accommodation + deposit = initial payment.')}</p><div id="estimateBreakdown" hidden><dl><div><dt id="estimateStay"></dt><dd id="estimateRate"></dd></div><div><dt>${t(lang,'Jumlah sewaan','Accommodation subtotal')}</dt><dd id="estimateTotal"></dd></div><div><dt>${t(lang,'Deposit berasingan','Separate deposit')}</dt><dd id="estimateDeposit">${money(b.securityDeposit)}</dd></div></dl><div class="estimate-total estimate-payable"><span>${t(lang,'Jumlah bayaran awal','Initial payment total')}</span><strong id="estimatePayable"></strong></div><p id="estimateEquation" class="estimate-equation"></p><p class="estimate-refund">${t(lang,'Deposit dipulangkan selepas check-out apabila pemeriksaan rumah memuaskan. Deposit hangus jika berlaku kerosakan atau perkara tidak diingini.','The deposit is refunded after check-out once the house inspection is satisfactory. It is forfeited if damage or unwanted incidents occur.')}</p></div><p class="estimate-caveat">${t(lang,'Anggaran termasuk deposit pilihan anda, belum termasuk caj tambahan. Owner mengesahkan kategori deposit, kekosongan, harga akhir dan aturan bayaran.','The estimate includes your selected deposit and excludes extra charges. The owner confirms the deposit category, availability, final price and payment arrangements.')}</p></div>
      <details id="familyPlan" class="family-plan" hidden data-share-url="${e(b.siteUrl.replace(/\/$/,'')+(lang==='en'?'/en.html':'/'))}"><summary>${t(lang,'Semak ringkasan untuk keluarga','Review a summary for your family')} ${icon('share')}</summary><div class="family-plan-content"><p>${t(lang,'Semak pakej, tarikh dan anggaran ini sebelum berkongsi. Nota peribadi dan jumlah tetamu tidak disertakan.','Review the package, dates and estimate before sharing. Private notes and guest counts are not included.')}</p><pre id="familyPlanText"></pre><button id="familyPlanShare" class="button" type="button">${icon('share')} ${t(lang,'Kongsi ringkasan','Share summary')}</button><p id="familyPlanFeedback" role="status" aria-live="polite"></p><div id="familyPlanFallback" hidden><label for="familyPlanCopyText">${t(lang,'Ringkasan untuk disalin','Summary to copy')}</label><textarea id="familyPlanCopyText" readonly rows="9" spellcheck="false"></textarea></div></div></details>
      <details id="enquiryPreview" class="enquiry-preview" hidden><summary>${t(lang,'Semak mesej pertanyaan','Review your enquiry message')} <span aria-hidden="true">+</span></summary><pre id="enquiryPreviewText"></pre></details>
      <button class="button form-submit" type="submit">${t(lang,'Buka pertanyaan di WhatsApp','Open enquiry in WhatsApp')} ${icon('arrow')}</button><p id="formFeedback" class="form-feedback" role="status" aria-live="polite"></p>
      <div class="enquiry-fallback"><a id="enquiryLink" class="text-link" hidden target="_blank" rel="noopener">${t(lang,'Buka semula mesej WhatsApp','Open the WhatsApp message again')}</a><button id="enquiryCopyMessage" class="text-button" type="button" hidden>${t(lang,'Salin mesej','Copy message')}</button></div>
      <p id="enquiryCopyFeedback" class="form-feedback" role="status" aria-live="polite"></p><div id="enquiryCopyFallback" hidden><label for="enquiryCopyText">${t(lang,'Mesej pertanyaan untuk disalin','Enquiry message to copy')}</label><textarea id="enquiryCopyText" readonly rows="9" spellcheck="false" aria-describedby="enquiryCopyFeedback"></textarea></div>
    <div class="draft-controls"><button id="clearEnquiryDraft" class="text-button" type="button" hidden>${t(lang,'Kosongkan borang','Clear form')}</button><p id="draftFeedback" class="field-note" role="status" aria-live="polite"></p></div></form></div>
  </div></section>`;
}

module.exports={renderEnquiry};
