const {config,e,t,wa,money,icon,picture,homeHref,pageHref,policyText,layout}=require('./shared.cjs');
const {renderGuideJourney}=require('./guide-journeys.cjs');
function renderPolicies(lang) {
  const topics=config.policies.map(item=>({key:item.key,title:policyText(item,lang)[0]}));
  topics.push({key:'privacy',title:t(lang,'Privasi ringkas','Privacy at a glance')});
  const body=`<article class="wrap document-page policy-page">
    <div class="document-heading"><p class="eyebrow">JITRA2STAY</p><h1>${t(lang,'Polisi & house rules','Policies & house rules')}</h1><p class="document-lead">${t(lang,'Perkara penting untuk dibincang sebelum bayaran dan dipatuhi sepanjang penginapan.','What to agree on before payment, and what to keep in mind during your stay.')}</p><a class="text-link" href="${homeHref(lang)}#kadar">${t(lang,'Kembali ke pakej bilik','Back to room packages')} ${icon('arrow')}</a></div>
    <div class="policy-layout">
      <nav class="policy-toc" id="policyContents" aria-labelledby="policyContentsTitle"><h2 id="policyContentsTitle">${t(lang,'Cari mengikut topik','Find a topic')}</h2><ul>${topics.map(item=>`<li><a href="#${e(item.key)}">${e(item.title)} ${icon('arrow')}</a></li>`).join('')}</ul></nav>
      <div class="document-content">${config.policies.map(item=>{const [title,description]=policyText(item,lang);return `<section id="${e(item.key)}" tabindex="-1"><h2>${e(title)}</h2><p>${e(description)}</p></section>`;}).join('')}<section id="privacy" tabindex="-1"><h2>${t(lang,'Privasi ringkas','Privacy at a glance')}</h2><p>${t(lang,'Butiran borang digunakan untuk menyediakan mesej WhatsApp. Draf disimpan sementara dalam tab browser ini dengan tempoh sah 2 jam supaya butiran kekal semasa menukar bahasa atau memuat semula halaman. Tekan “Kosongkan borang” untuk memadam draf. Website tidak menghantar borang ke server tempahan. Pilihan tema disimpan pada peranti; website tidak memasang alat analytics pengunjung sendiri.','Form details prepare your WhatsApp message. A temporary draft in this browser tab is valid for 2 hours so your details survive language changes or reloads. Press “Clear form” to remove it. The website does not send the form to a booking server. Your theme preference is stored on your device; we do not run visitor analytics.')}</p><p>${t(lang,'Peta Google Maps dalam halaman lokasi dimuat terus daripada Google. Peta tersebut serta pautan Google Maps, Waze dan WhatsApp menggunakan perkhidmatan serta dasar privasi pihak berkenaan. Jangan masukkan maklumat sensitif yang tidak diperlukan dalam pertanyaan awal.','The Google Maps view on the location section loads directly from Google. That map and the Google Maps, Waze and WhatsApp links use those providers’ services and privacy policies. Avoid including unnecessary sensitive information in your initial enquiry.')}</p></section><aside class="document-callout"><h2>${t(lang,'Ada syarat yang belum jelas?','Need a term clarified?')}</h2><p>${t(lang,'Minta pengesahan owner secara bertulis melalui WhatsApp sebelum membuat bayaran.','Ask the owner for written confirmation on WhatsApp before making a payment.')}</p><a class="button" href="${wa(lang,t(lang,'Hai Jitra2Stay, saya nak sahkan polisi, deposit dan syarat pembatalan sebelum membuat tempahan.','Hi Jitra2Stay, I would like to confirm the policies, deposit and cancellation terms before booking.'))}" target="_blank" rel="noopener">${t(lang,'Tanya owner','Ask the owner')} ${icon('arrow')}</a></aside></div>
    </div>
  </article>`;
  return layout({lang,title:t(lang,'Polisi & house rules | Jitra2Stay','Policies & house rules | Jitra2Stay'),description:t(lang,'Maklumat deposit, jumlah tetamu, waktu check-in dan house rules Jitra2Stay. Baca syarat pembatalan dan kaedah bayaran sebelum menginap.','Deposit, guest count, arrival times and house rules for Jitra2Stay. Read the cancellation terms and payment methods before your stay.'),path:pageHref('policies',lang),pairedPath:pageHref('policies',lang==='en'?'ms':'en'),body});
}
function renderGuide(guide,lang) {
  const copy=guide[lang], b=config.business;
  const waze=new URL('https://www.waze.com/ul');
  waze.searchParams.set('ll',`${b.coordinates.latitude},${b.coordinates.longitude}`);
  waze.searchParams.set('navigate','yes');
  const body=`<article class="wrap document-page guide-page"><div class="document-heading"><a class="breadcrumb" href="${homeHref(lang)}#lokasi">${t(lang,'Jitra2Stay / Lokasi','Jitra2Stay / Location')}</a><p class="eyebrow">${e(copy[1])}</p><h1>${e(copy[0])}</h1><p class="document-lead">${e(copy[2])}</p></div>
    <div class="guide-layout">
      <div class="document-content"><section><h2>${t(lang,'Rancang penginapan anda','Plan your stay')}</h2>${renderGuideJourney(copy[3],lang,guide.journeyStops)}</section><section><h2>${t(lang,'Pilih pakej yang sesuai','Choose a suitable package')}</h2><p>${t(lang,`Pilih antara 2 hingga ${b.bedrooms} bilik. Bincang susunan tidur, jumlah tetamu dan sebarang keperluan khusus dengan owner.`,`Choose from 2 to ${b.bedrooms} rooms. Discuss sleeping arrangements, guest count and any specific requirements with the owner.`)}</p><ul class="guide-rates">${config.rates.map(r=>`<li><span>${r.rooms} ${t(lang,'bilik','rooms')}</span><strong>${money(r.price)} / ${t(lang,'malam','night')}</strong></li>`).join('')}</ul><p class="small-note">${t(lang,'Kadar asas; deposit dan caj tambahan tidak termasuk. Tarikh dan harga akhir disahkan oleh owner.','Base rates exclude the deposit and additional charges. The owner confirms dates and the final price.')}</p></section><div class="button-row"><a class="button" href="${wa(lang,t(lang,`Hai Jitra2Stay, saya nak tanya tentang penginapan. Rujukan: ${copy[0]}.`,`Hi Jitra2Stay, I would like to ask about a stay. Reference: ${copy[0]}.`))}" target="_blank" rel="noopener">${t(lang,'Tanya melalui WhatsApp','Enquire on WhatsApp')} ${icon('arrow')}</a><a class="text-link" href="${homeHref(lang)}#galeri">${t(lang,'Lihat semua gambar','Explore the photos')}</a></div></div>
      <aside class="guide-aside" aria-labelledby="guideLocationTitle"><div><h2 id="guideLocationTitle">${t(lang,'Mulakan dari pin rumah','Start from the house pin')}</h2><address>${e(b.address.street)}<br>${e(b.address.postalCode)} ${e(b.address.city)}, ${e(b.address.region)}</address><div class="guide-directions"><a class="text-link" data-navigation="google" href="${e(b.mapUrl)}" target="_blank" rel="noopener">Google Maps ${icon('arrow')}</a><a class="text-link" data-navigation="waze" href="${e(waze.href)}" target="_blank" rel="noopener">Waze ${icon('arrow')}</a></div></div>${picture('ruang-tamu',t(lang,'Ruang tamu Jitra2Stay','Jitra2Stay living room'),{sizes:'(max-width: 900px) calc(100vw - 40px), 380px'})}</aside>
      <section class="related-guides" aria-labelledby="relatedGuidesTitle"><h2 id="relatedGuidesTitle">${t(lang,'Panduan lain','More local guides')}</h2><div class="related-guide-links">${config.guides.filter(g=>g.slug!==guide.slug).map(g=>`<a href="${pageHref(g.slug,lang)}"><span>${e(g[lang][0])}</span>${icon('arrow')}</a>`).join('')}</div></section>
    </div>
  </article>`;
  return layout({lang,title:`${copy[0]} | Jitra2Stay`,description:copy[2],path:pageHref(guide.slug,lang),pairedPath:pageHref(guide.slug,lang==='en'?'ms':'en'),body});
}
function renderThanks(lang) {
  return layout({lang,noindex:true,title:t(lang,'Sambung pertanyaan | Jitra2Stay','Continue your enquiry | Jitra2Stay'),description:t(lang,'Hubungi owner untuk menyemak tarikh dan pakej Jitra2Stay.','Contact the owner to discuss Jitra2Stay dates and room packages.'),path:pageHref('thank-you',lang),pairedPath:pageHref('thank-you',lang==='en'?'ms':'en'),body:`<section class="wrap recovery-page"><p class="eyebrow">JITRA2STAY</p><h1>${t(lang,'Sambung berbual<br>dengan owner.','Continue the conversation<br>with the owner.')}</h1><p>${t(lang,'Untuk semak tarikh dan harga akhir, hubungi owner melalui WhatsApp. Mesej perlu dihantar dalam WhatsApp; tempahan hanya sah selepas pengesahan owner.','For dates and a final price, contact the owner on WhatsApp. Send your message there; a booking is only confirmed by the owner.')}</p><div class="button-row"><a class="button" href="${wa(lang)}" target="_blank" rel="noopener">WhatsApp ${icon('arrow')}</a><a class="text-link" href="${homeHref(lang)}#semak-tarikh">${t(lang,'Sediakan butiran pertanyaan','Prepare enquiry details')}</a></div></section>`});
}
function render404() {
  // Error responses retain the requested URL, which may be nested under any path.
  // Inline styles and absolute recovery links also work on GitHub Pages' subpath.
  const home = new URL('/', config.business.siteUrl).href;
  return `<!doctype html><html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,follow"><title>Halaman tidak ditemui | Jitra2Stay</title><meta name="description" content="Kembali ke halaman utama Jitra2Stay atau hubungi owner."><link rel="canonical" href="${e(new URL('404.html', home).href)}"><style>
  *{box-sizing:border-box}body{margin:0;background:#f7f8f4;color:#183a2d;font:1rem/1.7 system-ui,sans-serif}main{max-width:760px;margin:auto;padding:clamp(48px,12vh,130px) 24px}p{max-width:56ch}h1{font:500 clamp(2.4rem,7vw,4.5rem)/1.08 Georgia,serif;letter-spacing:-.04em}a{color:inherit;text-underline-offset:5px}.button{display:inline-flex;align-items:center;gap:12px;min-height:48px;padding:12px 20px;border-radius:8px;background:#185d42;color:white;text-decoration:none}.button svg{width:20px;height:20px}.links{display:flex;align-items:center;gap:24px;flex-wrap:wrap;margin:32px 0}a:focus-visible{outline:3px solid #b2531d;outline-offset:5px}@media(prefers-color-scheme:dark){body{background:#13251e;color:#e7efe8}.button{background:#b9e4c6;color:#163828}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
  </style></head><body><main><p>JITRA2STAY · 404</p><h1>Halaman tidak ditemui.</h1><p>Pautan ini mungkin sudah berubah. Anda boleh kembali melihat rumah, gambar dan pakej penginapan.</p><div class="links"><a class="button" href="${e(home)}">Kembali ke laman utama ${icon('arrow')}</a><a href="${e(new URL('en.html', home).href)}" lang="en">View the website in English</a></div><p>Perlukan bantuan? <a href="${wa('ms')}" target="_blank" rel="noopener">Hubungi owner melalui WhatsApp</a>.</p></main></body></html>`;
}
module.exports={renderPolicies,renderGuide,renderThanks,render404};
