const {config,t,wa,money,icon,pageHref}=require('./shared.cjs');
const {renderStaySummary}=require('./stay-info.cjs');
function renderRates(lang) {
  const b=config.business;
  return `<section class="section section-tint" id="kadar" aria-labelledby="ratesTitle"><div class="wrap rates-layout">
    <div class="rates-intro"><p class="eyebrow">${t(lang,'PILIH IKUT KEPERLUAN','CHOOSE WHAT YOU NEED')}</p><h2 id="ratesTitle">${t(lang,'Ruang yang sesuai. Kadar yang jelas.','The right space. A clear starting rate.')}</h2><p>${t(lang,'Pakej 2 hingga 5 bilik dengan privasi satu rumah. Setiap pakej termasuk bilik air dengan water heater dan WiFi percuma.','Choose 2 to 5 bedrooms with full-house privacy. Every package includes bathrooms with water heaters and free WiFi.')}</p></div>
    <div class="package-options"><div id="stayComparison" class="stay-comparison" hidden><fieldset><legend>${t(lang,'Bandingkan jumlah sewaan','Compare accommodation totals')}</legend><div class="comparison-nights">${[1,2,3].map(n=>`<button type="button" data-compare-nights="${n}" aria-pressed="${n===1}">${n} ${t(lang,'malam',n===1?'night':'nights')}</button>`).join('')}</div></fieldset><div class="comparison-help"><p id="comparisonStatus" role="status" aria-live="polite"></p><a href="#semak-tarikh">${t(lang,'Tetapkan tarikh atau tempoh lebih lama','Set dates or a longer stay')} ${icon('arrow')}</a></div></div><p class="package-hint">${t(lang,'Pilih pakej untuk terus ke pertanyaan tarikh.','Choose a package to enquire about your dates.')}</p><div class="package-grid">${config.rates.map(rate=>`<article class="package-card" data-package="${rate.rooms}" aria-labelledby="packageTitle${rate.rooms}"><div class="package-heading">${icon('bed')}<h3 id="packageTitle${rate.rooms}">${rate.rooms} ${t(lang,'bilik','rooms')}</h3></div><p class="package-bathrooms"><span>${rate.bathrooms} ${t(lang,'bilik air','bathrooms')}</span><span>${t(lang,'Water heater','Water heaters')}</span></p><p class="package-price"><strong>${money(rate.price)}</strong><span>/ ${t(lang,'malam','night')}</span></p><div class="package-total" hidden><span class="package-total-label"></span><strong class="package-total-value"></strong></div><a class="package-link" href="#semak-tarikh" data-rooms="${rate.rooms}" aria-label="${t(lang,`Pilih pakej ${rate.rooms} bilik`,`Choose the ${rate.rooms}-room package`)}">${t(lang,'Pilih','Choose')} ${icon('arrow')}</a><span class="package-selected" hidden>${icon('check')}${t(lang,'Pilihan anda','Your selection')}</span></article>`).join('')}</div>
      <div class="package-meta">
      <p class="rate-note" id="rateNote">${t(lang,'Kadar asas semalam, tidak termasuk deposit atau caj tambahan. Penginapan 2 malam ke atas boleh bertanya tentang kadar terbaik melalui WhatsApp.','Base nightly rates exclude the deposit and extra charges. For stays of 2 nights or more, ask about the best available rate on WhatsApp.')}</p>
      <div class="payment-example"><strong>${t(lang,'Contoh bayaran: 2 bilik, 1 malam','Payment example: 2 rooms, 1 night')}</strong><p>${t(lang,`Sewaan ${money(config.rates[0].price)} + deposit biasa ${money(b.securityDeposit)}`,`Accommodation ${money(config.rates[0].price)} + standard deposit ${money(b.securityDeposit)}`)} <span>= ${money(config.rates[0].price+b.securityDeposit)}</span></p><p>${t(lang,`Deposit ${money(b.securityDeposit)} dipulangkan selepas pemeriksaan rumah memuaskan. Deposit hangus jika berlaku kerosakan atau perkara tidak diingini.`,`The ${money(b.securityDeposit)} deposit is refunded after a satisfactory house inspection and forfeited if damage or unwanted incidents occur.`)}</p></div>
      <details class="rate-examples"><summary>${t(lang,'Contoh kongsi kos seorang','Example cost per person')}</summary><ul>${config.rates.map(rate=>`<li><span>${rate.rooms} ${t(lang,'bilik','rooms')} · ${rate.exampleGuests} ${t(lang,'orang','people')}</span><strong>≈${money(Math.round(rate.price/rate.exampleGuests))} / ${t(lang,'orang','person')}</strong></li>`).join('')}</ul><p>${t(lang,`Contoh pembahagian kadar semalam, bukan had tetamu setiap pakej. Maksimum rumah ${b.maxGuests} orang termasuk kanak-kanak.`,`Examples divide the nightly rate; they are not package occupancy limits. The house maximum is ${b.maxGuests} guests including children.`)}</p></details></div>
    </div>
    <div class="rates-support"><div class="deposit-note">${icon('check')}<div><strong>${t(lang,'Deposit keselamatan','Security deposit')} ${money(b.securityDeposit)} / ${money(b.largeGroupSecurityDeposit)}</strong><p>${t(lang,`${money(b.securityDeposit)} untuk penginapan biasa atau kumpulan kecil; ${money(b.largeGroupSecurityDeposit)} untuk rombongan besar atau majlis besar seperti kenduri. Kategori disahkan oleh owner.`,`${money(b.securityDeposit)} for regular stays or small groups; ${money(b.largeGroupSecurityDeposit)} for large groups or major events such as weddings. The owner confirms the category.`)}</p></div></div>
      <div class="extra-guest-note">${icon('people')}<div><strong>${t(lang,`Tetamu tambahan RM${b.extraGuestFee} seorang`,`Extra guests RM${b.extraGuestFee} per person`)}</strong><p>${t(lang,`Had maksimum ${b.maxGuests} orang termasuk kanak-kanak.`,`Maximum ${b.maxGuests} guests including children.`)}</p></div></div><div class="rates-support-links"><a class="text-link" href="${pageHref('policies',lang)}">${t(lang,'Polisi penginapan','Stay policies')} ${icon('arrow')}</a>
      <p class="package-help"><a href="${wa(lang,t(lang,'Hai Jitra2Stay, saya berminat untuk menginap 2 malam atau lebih. Boleh semak tarikh dan kadar?','Hi Jitra2Stay, I am interested in staying for 2 nights or more. Could I check dates and rates?'))}" target="_blank" rel="noopener">${t(lang,'Tanya kadar 2+ malam','Ask about 2+ nights')} ${icon('arrow')}</a></p>
    </div></div>
    ${renderStaySummary(lang)}
  </div></section>`;
}
module.exports={renderRates};
