const {config,e,t,wa,money,icon,picture,policy,pageHref,layout}=require('./shared.cjs');
const {renderGallery}=require('./gallery.cjs');
const {renderRates}=require('./rates.cjs');
const {renderEnquiry}=require('./enquiry.cjs');
const {renderLocation}=require('./location.cjs');
function renderHome(lang) {
  const b=config.business, isEn=lang==='en', min=config.rates[0].price;
  const faq=[
    [t(lang,'Bagaimana pakej bilik berfungsi?','How do room packages work?'),t(lang,'Pilih 2 hingga 5 bilik mengikut keperluan anda. Sahkan bilik yang dibuka, susunan katil dan penggunaan ruang rumah dengan owner sebelum membuat bayaran.','Choose 2 to 5 rooms for your stay. Confirm which rooms are open, the bed arrangement and use of the house with the owner before paying.')],
    [t(lang,'Berapa orang boleh menginap?','How many guests can stay?'),policy('capacity',lang)[1]],
    [t(lang,'Adakah deposit diperlukan?','Is a deposit required?'),policy('deposit',lang)[1]],
    [t(lang,'Boleh batal atau tukar tarikh?','Can I cancel or change dates?'),policy('cancellation',lang)[1]],
    [t(lang,'Bagaimana dengan parking?','What about parking?'),t(lang,'Parking di kawasan rumah tersedia. Sahkan kapasiti mengikut jumlah kereta anda; van atau bas memerlukan semakan awal dengan owner.','Parking is available at the house. Check space for your vehicle count; vans or coaches need advance discussion with the owner.')],
    [t(lang,'Adakah tuala dan kelengkapan dapur disediakan?','Are towels and kitchen supplies provided?'),t(lang,'Sahkan tuala, toiletries dan peralatan dapur khusus dengan owner sebelum datang. Bawa keperluan peribadi dan bahan makanan anda sendiri.','Check towels, toiletries and any specific kitchen equipment with the owner before arriving. Bring your personal essentials and food supplies.')],
    [t(lang,'Boleh bawa haiwan atau buat majlis?','Are pets or events allowed?'),t(lang,'Haiwan peliharaan tidak dibenarkan. Sebarang majlis perlu mendapat izin owner; jumlah tetamu, parking dan caj berkaitan mesti dipersetujui terlebih dahulu.','Pets are not allowed. Events need the owner’s permission; guest count, parking and any charges must be agreed in advance.')]
  ];
  const body=`
  <section class="hero wrap" id="home" aria-labelledby="heroTitle"><div class="hero-copy"><p class="eyebrow">${icon('pin')}${t(lang,'SEBELAH HOSPITAL JITRA','BESIDE JITRA HOSPITAL')}</p><h1 id="heroTitle">${t(lang,'Ruang untuk keluarga.<br>Rehat di Jitra.','Room for family.<br>Rest in Jitra.')}</h1><p class="hero-description">${t(lang,'Homestay Semi-D dua tingkat untuk menginap bersama. Lihat rumah, pilih pakej bilik dan bincang tarikh dengan owner.','A two-storey semi-detached homestay for time together. Explore the house, choose a room package and ask the owner about your dates.')}</p><p class="hero-rate">${t(lang,'Dari','From')} <strong>${money(min)}</strong><span> / ${t(lang,'malam','night')}</span></p><div class="hero-actions"><a class="button" id="heroPrimaryCta" href="${wa(lang)}" target="_blank" rel="noopener">${t(lang,'Tanya tarikh di WhatsApp','Ask about dates')} ${icon('arrow')}</a><a class="text-link" href="#galeri">${t(lang,'Lihat gambar rumah','Explore the photos')}</a></div><p class="hero-note">${t(lang,'Tarikh dan harga akhir disahkan oleh owner.','Dates and final rates are confirmed by the owner.')}</p></div><figure class="hero-media">${picture('halaman',t(lang,'Hadapan rumah Jitra2Stay di Taman Jitra Indah','Jitra2Stay exterior in Taman Jitra Indah'),{hero:true,sizes:'(max-width: 900px) calc(100vw - 40px), (max-width: 1280px) 53vw, 660px'})}<figcaption><span>${icon('home')} Jitra2Stay</span><span>Taman Jitra Indah, Kedah</span></figcaption></figure></section>
  <section class="facts-section" id="tentang" aria-label="${t(lang,'Ringkasan rumah','House at a glance')}"><div class="wrap facts-grid"><div class="fact">${icon('home')}<div><strong>${t(lang,'Semi-D','Semi-detached')}</strong><span>${t(lang,'Rumah dua tingkat','Two-storey house')}</span></div></div><div class="fact">${icon('bed')}<div><strong>${b.bedrooms} ${t(lang,'bilik tidur','bedrooms')}</strong><span>${t(lang,'Pakej 2 hingga 5 bilik','Packages from 2 to 5 rooms')}</span></div></div><div class="fact">${icon('bath')}<div><strong>${b.bathrooms} ${t(lang,'bilik air','bathrooms')}</strong><span>${t(lang,'Akses mengikut pakej','Access by room package')}</span></div></div><div class="fact">${icon('people')}<div><strong>${t(lang,'Maksimum','Up to')} ${b.maxGuests} ${t(lang,'tetamu','guests')}</strong><span>${t(lang,'Termasuk kanak-kanak','Including children')}</span></div></div></div><p class="wrap facts-note">${t(lang,'Beritahu owner jumlah tetamu dan keperluan tidur supaya pakej bilik sesuai untuk semua.','Share your guest count and sleeping needs so the owner can help you choose a suitable package.')}</p></section>
  ${renderGallery(lang)}
  ${renderRates(lang)}
  <section class="section wrap" id="kemudahan" aria-labelledby="amenitiesTitle"><div class="section-heading"><div><p class="eyebrow">${t(lang,'UNTUK PENGINAPAN ANDA','FOR YOUR STAY')}</p><h2 id="amenitiesTitle">${t(lang,'Keperluan untuk rasa selesa.','The essentials for settling in.')}</h2></div><p>${t(lang,'Ruang bersama dan kemudahan asas untuk keluarga. Sahkan keperluan khusus sebelum datang.','Shared spaces and everyday essentials for your family. Check any specific needs before arrival.')}</p></div><div class="amenities-grid">${config.facilities.map(f=>`<article class="amenity">${icon(f.icon)}<h3>${e(f[lang][0])}</h3><p>${e(f[lang][1])}</p></article>`).join('')}</div></section>
  ${renderLocation(lang)}
  <section class="section wrap faq-layout" id="faq" aria-labelledby="faqTitle"><div><p class="eyebrow">${t(lang,'SEBELUM ANDA DATANG','BEFORE YOU ARRIVE')}</p><h2 id="faqTitle">${t(lang,'Ada yang ingin<br>ditanya?','A few things<br>to know.')}</h2><p>${t(lang,'Semak perkara utama di sini, atau hubungi owner untuk keperluan penginapan anda.','Find the essentials here, or contact the owner about your particular stay.')}</p><a class="text-link" href="${pageHref('policies',lang)}">${t(lang,'Polisi & house rules penuh','Full policies & house rules')} ${icon('arrow')}</a></div><div class="faq-list">${faq.map(([question,answer])=>`<details><summary>${e(question)}<span aria-hidden="true">+</span></summary><p>${e(answer)}</p></details>`).join('')}</div></section>
  ${renderEnquiry(lang)}
`;
  return layout({lang,title:t(lang,'Jitra2Stay | Homestay keluarga di Jitra, Kedah','Jitra2Stay | Family homestay in Jitra, Kedah'),description:t(lang,`Homestay Semi-D di Jitra dengan ${b.bedrooms} bilik dan ${b.bathrooms} bilik air. Lihat foto, pakej dari RM${min}/malam dan lokasi. Tanya tarikh melalui WhatsApp.`,`A semi-detached homestay in Jitra with ${b.bedrooms} bedrooms and ${b.bathrooms} bathrooms. Explore photos, packages from RM${min}/night and the location. Enquire on WhatsApp.`),path:isEn?'en.html':'',pairedPath:isEn?'':'en.html',body,isHome:true});
}
module.exports={renderHome};
