const {config,t,wa,money,icon,pageHref}=require('./shared.cjs');
const {renderStaySummary}=require('./stay-info.cjs');
function renderRates(lang) {
  const b=config.business;
  return `<section class="section section-tint" id="kadar" aria-labelledby="ratesTitle"><div class="wrap rates-layout">
    <div class="rates-intro"><p class="eyebrow">${t(lang,'PILIH IKUT KEPERLUAN','CHOOSE WHAT YOU NEED')}</p><h2 id="ratesTitle">${t(lang,'Ruang yang sesuai.<br>Kadar yang jelas.','The right space.<br>A clear starting rate.')}</h2><p>${t(lang,'Pakej 2 hingga 5 bilik dengan privasi satu rumah. Setiap pakej termasuk bilik air dengan water heater dan WiFi percuma.','Choose 2 to 5 bedrooms with full-house privacy. Every package includes bathrooms with water heaters and free WiFi.')}</p></div>
    <div class="package-options"><div class="package-grid">${config.rates.map(rate=>`<article class="package-card" data-package="${rate.rooms}" aria-labelledby="packageTitle${rate.rooms}"><div class="package-heading">${icon('bed')}<h3 id="packageTitle${rate.rooms}">${rate.rooms} ${t(lang,'bilik','rooms')}</h3></div><p class="package-bathrooms">${rate.bathrooms} ${t(lang,'bilik air · water heater','bathrooms · water heaters')}</p><p class="package-price"><strong>${money(rate.price)}</strong><span>/ ${t(lang,'malam','night')}</span></p><a class="package-link" href="#semak-tarikh" data-rooms="${rate.rooms}" aria-label="${t(lang,`Pilih pakej ${rate.rooms} bilik`,`Choose the ${rate.rooms}-room package`)}">${t(lang,'Pilih','Choose')} ${icon('arrow')}</a><span class="package-selected" hidden>${icon('check')}${t(lang,'Pilihan anda','Your selection')}</span></article>`).join('')}</div>
      <p class="rate-note" id="rateNote">${t(lang,'Kadar asas semalam, tidak termasuk deposit atau caj tambahan. Penginapan 2 malam ke atas boleh bertanya tentang kadar terbaik melalui WhatsApp.','Base nightly rates exclude the deposit and extra charges. For stays of 2 nights or more, ask about the best available rate on WhatsApp.')}</p>
      <details class="rate-examples"><summary>${t(lang,'Contoh kongsi kos seorang','Example cost per person')}</summary><ul>${config.rates.map(rate=>`<li><span>${rate.rooms} ${t(lang,'bilik','rooms')} · ${rate.exampleGuests} ${t(lang,'orang','people')}</span><strong>≈${money(Math.round(rate.price/rate.exampleGuests))} / ${t(lang,'orang','person')}</strong></li>`).join('')}</ul><p>${t(lang,`Contoh pembahagian kadar semalam, bukan had tetamu setiap pakej. Maksimum rumah ${b.maxGuests} orang termasuk kanak-kanak.`,`Examples divide the nightly rate; they are not package occupancy limits. The house maximum is ${b.maxGuests} guests including children.`)}</p></details>
    </div>
    <div class="rates-support"><div class="deposit-note">${icon('check')}<div><strong>${t(lang,'Deposit keselamatan','Security deposit')} ${money(b.securityDeposit)}</strong><p>${t(lang,'Berasingan daripada sewaan. Dipulangkan selepas check-out jika tiada kerosakan atau pelanggaran house rules.','Separate from accommodation. Returned after check-out if there is no damage or house-rule breach.')}</p></div></div>
      <p class="extra-guest-note">${t(lang,`Caj tetamu tambahan RM${b.extraGuestFee} seorang. Had maksimum ${b.maxGuests} orang termasuk kanak-kanak.`,`Extra guests: RM${b.extraGuestFee} per person. Maximum ${b.maxGuests} guests including children.`)}</p><a class="text-link" href="${pageHref('policies',lang)}">${t(lang,'Baca polisi penginapan','Read the stay policies')} ${icon('arrow')}</a>
      <p class="package-help"><a href="${wa(lang,t(lang,'Hai Jitra2Stay, saya berminat untuk menginap 2 malam atau lebih. Boleh semak tarikh dan kadar?','Hi Jitra2Stay, I am interested in staying for 2 nights or more. Could I check dates and rates?'))}" target="_blank" rel="noopener">${t(lang,'Menginap lebih lama? Tanya kadar','Staying longer? Ask about rates')} ${icon('arrow')}</a></p>
    </div>
    ${renderStaySummary(lang)}
  </div></section>`;
}
module.exports={renderRates};
